# Generated by Django 5.2.4 on 2025-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrental',
            name='actual_check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
