# Generated by Django 5.2.4 on 2025-08-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmation', 'Xác nhận đặt phòng'), ('check_in_reminder', 'Nhắc nhở nhận phòng'), ('check_out_reminder', 'Nhắc nhở trả phòng'), ('payment_failed', 'Thanh toán thất bại'), ('promotion', 'Khuyến mãi')], max_length=20),
        ),
    ]
