# Generated by Django 5.2.4 on 2025-08-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelplatform', '0002_roomrental_actual_check_out_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='hotelplatfo_uuid_b0a6b5_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='uuid',
        ),
    ]
