# Generated by Django 5.2.4 on 2025-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelplatform', '0003_remove_booking_hotelplatfo_uuid_b0a6b5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrental',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
    ]
