# Generated by Django 5.2.4 on 2025-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelplatform', '0004_alter_roomrental_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='user_group',
            field=models.CharField(blank=True, choices=[('new', 'Khách hàng mới'), ('regular', 'Khách phổ thông'), ('vip', 'Khách VIP'), ('super_vip', 'Khách siêu VIP'), ('unknown', 'Không xác định')], help_text='Nhóm khách hàng áp dụng. Để trống nếu áp dụng cho tất cả.', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['user_group', 'is_active'], name='hotelplatfo_user_gr_f5d7d2_idx'),
        ),
    ]
